"""empty message

Revision ID: 9e42d2a884c2
Revises: 
Create Date: 2024-04-17 13:46:47.274953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e42d2a884c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hosts')),
    sa.UniqueConstraint('name', name=op.f('uq_hosts_name'))
    )
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('venue_picture', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venues'))
    )
    op.create_table('weddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food', sa.String(), nullable=True),
    sa.Column('entertainment', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_weddings_venue_id_venues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weddings'))
    )
    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_name', sa.String(), nullable=False),
    sa.Column('wedding_id', sa.Integer(), nullable=True),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], name=op.f('fk_invites_host_id_hosts')),
    sa.ForeignKeyConstraint(['wedding_id'], ['weddings.id'], name=op.f('fk_invites_wedding_id_weddings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invites'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invites')
    op.drop_table('weddings')
    op.drop_table('venues')
    op.drop_table('hosts')
    # ### end Alembic commands ###
